$PROJECT Trastuzumab: minimal PBPK with target-mediated disposition in interstitial fluid

$DIFFEQ_DIF

CP = X(1)/VP
CLY = X(4)/VLYMPH

CTOTT = X(2)/VTIGHT
IF (CTOTT.LT.0) CTOTT = 0
BTT = CTOTT - X(5) - KSS
DTT = SQRT(BTT*BTT + 4*KSS*CTOTT)
IF (BTT.GE.0) THEN
   CFT = 0.5*(BTT + DTT)
ELSE
   CFT = 2*KSS*CTOTT/(DTT - BTT)
ENDIF
ART = CTOTT - CFT

CTOTL = X(3)/VLEAKY
IF (CTOTL.LT.0) CTOTL = 0
BTL = CTOTL - X(6) - KSS
DTL = SQRT(BTL*BTL + 4*KSS*CTOTL)
IF (BTL.GE.0) THEN
   CFL = 0.5*(BTL + DTL)
ELSE
   CFL = 2*KSS*CTOTL/(DTL - BTL)
ENDIF
ARL = CTOTL - CFL

FLXT = (1 - SIGMA1)*LYMPH1*CP
FLXL = (1 - SIGMA2)*LYMPH2*CP
RETT = (1 - SIGL)*LYMPH1*CFT
RETL = (1 - SIGL)*LYMPH2*CFL

XP(1) = R(1) - FLXT - FLXL + LTOT*CLY - CLP*CP
XP(2) = FLXT - RETT - KINT*ART*VTIGHT
XP(3) = FLXL - RETL - KINT*ARL*VLEAKY
XP(4) = RETT + RETL - LTOT*CLY
XP(5) = KSYN - KDEG*X(5) - (KINT - KDEG)*ART
XP(6) = KSYN - KDEG*X(6) - (KINT - KDEG)*ARL


$OUTPUT_GLB

VP = 2.6
VISF = 15.6
VLYMPH = 5.2
LTOT = 0.120833
AVAIL = 0.8
SIGL = 0.2
LYMPH1 = 0.33*LTOT
LYMPH2 = 0.67*LTOT
VTIGHT = 0.65*VISF*AVAIL
VLEAKY = 0.35*VISF*AVAIL
KDEG = 0.0117
KINT = 0.0117
MWAB = 148000
RZERO = KSYN/KDEG


$OUTPUT_ICS

X(5) = X(5) + RZERO
X(6) = X(6) + RZERO


$OUTPUT_EQN

if (X(1).LT.0) X(1) = 0

Y(1) = X(1)/VP*MWAB/1E6


$VARMOD_EQN

V(1) = (SDIN + SDSL*Y(1))*(SDIN + SDSL*Y(1))


$POPMOD_EQN
